services:
  surfshark:
    image: gathecageorge/docker-surfshark-qbittorrent
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - SURFSHARK_USER=${SURFSHARK_USER}
      - SURFSHARK_PASSWORD=${SURFSHARK_PASSWORD}
      - SURFSHARK_COUNTRY=${SURFSHARK_COUNTRY:-}
      - SURFSHARK_CITY=${SURFSHARK_CITY:-}
      - CONNECTION_TYPE=${CONNECTION_TYPE:-udp}
      - LAN_NETWORK=${LAN_NETWORK:-}
      - WEBUI_PORT=${WEBUI_PORT:-8080}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
    restart: unless-stopped
    dns:
      - 1.1.1.1
